#ifndef GUARD_CONSTANTS_OPPONENTS_HNS_H
#define GUARD_CONSTANTS_OPPONENTS_HNS_H

#include "constants/battle_partner.h"

#define TRAINER_NONE                               0

// HnS Trainers
#define TRAINER_SAWYER_1_HNS                          1
#define TRAINER_ROSS_HNS                              2
#define TRAINER_MITCH_HNS                             3
#define TRAINER_JED_HNS                               4
#define TRAINER_MARC_HNS                              5
#define TRAINER_RICH_HNS                              6
#define TRAINER_JOEY_HNS                              7
#define TRAINER_MIKEY_HNS                             8
#define TRAINER_ALBERT_HNS                            9
#define TRAINER_GORDON_HNS                            10
#define TRAINER_SAMUEL_HNS                            11
#define TRAINER_IAN_HNS                               12
#define TRAINER_WARREN_HNS                            13
#define TRAINER_JIMMY_HNS                             14
#define TRAINER_OWEN_HNS                              15
#define TRAINER_JASON_HNS                             16
#define TRAINER_JACK_HNS                              17
#define TRAINER_KIPP_HNS                              18
#define TRAINER_ALAN_HNS                              19
#define TRAINER_JOHNNY_HNS                            20
#define TRAINER_DANNY_HNS                             21
#define TRAINER_TOMMY_HNS                             22
#define TRAINER_DUDLEY_HNS                            23
#define TRAINER_JOE_HNS                               24
#define TRAINER_BILLY_HNS                             25
#define TRAINER_CHAD_HNS                              26
#define TRAINER_NATE_HNS                              27
#define TRAINER_RICKY_HNS                             28
#define TRAINER_ROD_HNS                               29
#define TRAINER_ABE_HNS                               30
#define TRAINER_BRYAN_HNS                             31
#define TRAINER_THEO_HNS                              32
#define TRAINER_TOBY_HNS                              33
#define TRAINER_DENIS_HNS                             34
#define TRAINER_VANCE_HNS                             35
#define TRAINER_HANK_HNS                              36
#define TRAINER_ROY_HNS                               37
#define TRAINER_BORIS_HNS                             38
#define TRAINER_BOB_HNS                               39
#define TRAINER_JOSE_HNS                              40
#define TRAINER_PETER_HNS                             41
#define TRAINER_PERRY_HNS                             42
#define TRAINER_BRET_HNS                              43
#define TRAINER_CARRIE_HNS                            44
#define TRAINER_BRIDGET_HNS                           45
#define TRAINER_ALICE_HNS                             46
#define TRAINER_KRISE_HNS                             47
#define TRAINER_CONNIE_HNS                            48
#define TRAINER_LINDA_HNS                             49
#define TRAINER_LAURA_HNS                             50
#define TRAINER_SHANNON_HNS                           51
#define TRAINER_MICHELLE_HNS                          52
#define TRAINER_DANA_HNS                              53
#define TRAINER_ELLEN_HNS                             54
#define TRAINER_NICK_HNS                              55
#define TRAINER_AARON_HNS                             56
#define TRAINER_PAUL_HNS                              57
#define TRAINER_CODY_HNS                              58
#define TRAINER_MIKE_HNS                              59
#define TRAINER_GAVEN_HNS                             60
#define TRAINER_RYAN_HNS                              61
#define TRAINER_JAKE_HNS                              62
#define TRAINER_BLAKE_HNS                             63
#define TRAINER_BRIAN_HNS                             64
#define TRAINER_ERICK_HNS                             65
#define TRAINER_ANDY_HNS                              66
#define TRAINER_TYLER_HNS                             67
#define TRAINER_SEAN_HNS                              68
#define TRAINER_KEVIN_HNS                             69
#define TRAINER_STEVE_HNS                             70
#define TRAINER_ALLEN_HNS                             71
#define TRAINER_DARIN_HNS                             72
#define TRAINER_GWEN_HNS                              73
#define TRAINER_LOIS_HNS                              74
#define TRAINER_FRAN_HNS                              75
#define TRAINER_LOLA_HNS                              76
#define TRAINER_KATE_HNS                              77
#define TRAINER_IRENE_HNS                             78
#define TRAINER_KELLY_HNS                             79
#define TRAINER_JOYCE_HNS                             80
#define TRAINER_BETH_HNS                              81
#define TRAINER_REENA_HNS                             82
#define TRAINER_MEGAN_HNS                             83
#define TRAINER_CAROL_HNS                             84
#define TRAINER_QUINN_HNS                             85
#define TRAINER_EMMA_HNS                              86
#define TRAINER_CYBIL_HNS                             87
#define TRAINER_JENN_HNS                              88
#define TRAINER_CARA_HNS                              89
#define TRAINER_VICTORIA_HNS                          90
#define TRAINER_SAMANTHA_HNS                          91
#define TRAINER_JULIE_HNS                             92
#define TRAINER_JACLYN_HNS                            93
#define TRAINER_BRENDA_HNS                            94
#define TRAINER_CASSIE_HNS                            95
#define TRAINER_CAROLINE_HNS                          96
#define TRAINER_CARLENE_HNS                           97
#define TRAINER_JESSICA_HNS                           98
#define TRAINER_RACHAEL_HNS                           99
#define TRAINER_ANGELICA_HNS                          100
#define TRAINER_KENDRA_HNS                            101
#define TRAINER_VERONICA_HNS                          102
#define TRAINER_JULIA_HNS                             103
#define TRAINER_THERESA_HNS                           104
#define TRAINER_VALERIE_HNS                           105
#define TRAINER_OLIVIA_HNS                            106
#define TRAINER_LARRY_HNS                             107
#define TRAINER_ANDREW_HNS                            108
#define TRAINER_CALVIN_HNS                            109
#define TRAINER_SHANE_HNS                             110
#define TRAINER_BEN_HNS                               111
#define TRAINER_BRENT_HNS                             112
#define TRAINER_RON_HNS                               113
#define TRAINER_ETHAN_HNS                             114
#define TRAINER_ISSAC_HNS                             115
#define TRAINER_DONALD_HNS                            116
#define TRAINER_ZACH_HNS                              117
#define TRAINER_MILLER_HNS                            118
#define TRAINER_GRUNT_HNS                             119
#define TRAINER_GRUNT_2_HNS                           120
#define TRAINER_GRUNT_3_HNS                           121
#define TRAINER_GRUNT_4_HNS                           122
#define TRAINER_GRUNT_5_HNS                           123
#define TRAINER_GRUNT_6_HNS                           124
#define TRAINER_GRUNT_7_HNS                           125
#define TRAINER_GRUNT_8_HNS                           126
#define TRAINER_GRUNT_9_HNS                           127
#define TRAINER_GRUNT_10_HNS                          128
#define TRAINER_GRUNT_11_HNS                          129
#define TRAINER_GRUNT_12_HNS                          130
#define TRAINER_GRUNT_13_HNS                          131
#define TRAINER_GRUNT_14_HNS                          132
#define TRAINER_GRUNT_15_HNS                          133
#define TRAINER_GRUNT_16_HNS                          134
#define TRAINER_GRUNT_17_HNS                          135
#define TRAINER_GRUNT_18_HNS                          136
#define TRAINER_GRUNT_19_HNS                          137
#define TRAINER_GRUNT_20_HNS                          138
#define TRAINER_GRUNT_21_HNS                          139
#define TRAINER_GRUNT_22_HNS                          140
#define TRAINER_GRUNT_23_HNS                          141
#define TRAINER_GRUNT_24_HNS                          142
#define TRAINER_GRUNT_25_HNS                          143
#define TRAINER_GRUNT_26_HNS                          144
#define TRAINER_GRUNT_27_HNS                          145
#define TRAINER_GRUNT_28_HNS                          146
#define TRAINER_GRUNT_29_HNS                          147
#define TRAINER_GRUNT_30_HNS                          148
#define TRAINER_GRUNT_31_HNS                          149
#define TRAINER_GRUNT_32_HNS                          150
#define TRAINER_GRUNT_33_HNS                          151
#define TRAINER_ETO_HNS                               152
#define TRAINER_ETO_2_HNS                             153
#define TRAINER_ETO_3_HNS                             154
#define TRAINER_PRESTON_HNS                           155
#define TRAINER_EDWARD_HNS                            156
#define TRAINER_GREGORY_HNS                           157
#define TRAINER_VIRGIL_HNS                            158
#define TRAINER_ALFRED_HNS                            159
#define TRAINER_ROXANNE_HNS                           160
#define TRAINER_CLARISSA_HNS                          161
#define TRAINER_COLETTE_HNS                           162
#define TRAINER_HILLARY_HNS                           163
#define TRAINER_SHIRLEY_HNS                           164
#define TRAINER_DON_HNS                               165
#define TRAINER_ROB_HNS                               166
#define TRAINER_ED_HNS                                167
#define TRAINER_WADE_HNS                              168
#define TRAINER_BENNY_HNS                             169
#define TRAINER_AL_HNS                                170
#define TRAINER_JOSH_HNS                              171
#define TRAINER_ARNIE_HNS                             172
#define TRAINER_KEN_HNS                               173
#define TRAINER_DOUG_HNS                              174
#define TRAINER_WAYNE_HNS                             175
#define TRAINER_JUSTIN_HNS                            176
#define TRAINER_RALPH_HNS                             177
#define TRAINER_ARNOLD_HNS                            178
#define TRAINER_KYLE_HNS                              179
#define TRAINER_HENRY_HNS                             180
#define TRAINER_MARVIN_HNS                            181
#define TRAINER_TULLY_HNS                             182
#define TRAINER_ANDRE_HNS                             183
#define TRAINER_RAYMOND_HNS                           184
#define TRAINER_WILTON_HNS                            185
#define TRAINER_EDGAR_HNS                             186
#define TRAINER_JONAH_HNS                             187
#define TRAINER_MARTIN_HNS                            188
#define TRAINER_STEPHEN_HNS                           189
#define TRAINER_BARNEY_HNS                            190
#define TRAINER_SCOTT_HNS                             191
#define TRAINER_HAROLD_HNS                            192
#define TRAINER_SIMON_HNS                             193
#define TRAINER_RANDALL_HNS                           194
#define TRAINER_CHARLIE_HNS                           195
#define TRAINER_GEORGE_HNS                            196
#define TRAINER_BERKE_HNS                             197
#define TRAINER_KIRK_HNS                              198
#define TRAINER_MATHEW_HNS                            199
#define TRAINER_HAL_HNS                               200
#define TRAINER_PATON_HNS                             201
#define TRAINER_DARYL_HNS                             202
#define TRAINER_WALTER_HNS                            203
#define TRAINER_TONY_HNS                              204
#define TRAINER_JEROME_HNS                            205
#define TRAINER_TUCKER_HNS                            206
#define TRAINER_RICK_HNS                              207
#define TRAINER_CAMERON_HNS                           208
#define TRAINER_SETH_HNS                              209
#define TRAINER_JAMES_HNS                             210
#define TRAINER_LEWIS_HNS                             211
#define TRAINER_PARKER_HNS                            212
#define TRAINER_ELAINE_HNS                            213
#define TRAINER_PAULA_HNS                             214
#define TRAINER_KAYLEE_HNS                            215
#define TRAINER_SUSIE_HNS                             216
#define TRAINER_DENISE_HNS                            217
#define TRAINER_KARA_HNS                              218
#define TRAINER_WENDY_HNS                             219
#define TRAINER_LISA_HNS                              220
#define TRAINER_JILL_HNS                              221
#define TRAINER_MARY_HNS                              222
#define TRAINER_KATIE_HNS                             223
#define TRAINER_DAWN_HNS                              224
#define TRAINER_TARA_HNS                              225
#define TRAINER_NICOLE_HNS                            226
#define TRAINER_LORI_HNS                              227
#define TRAINER_JODY_HNS                              228
#define TRAINER_NIKKI_HNS                             229
#define TRAINER_DIANA_HNS                             230
#define TRAINER_BRIANA_HNS                            231
#define TRAINER_EUGENE_HNS                            232
#define TRAINER_HUEY_HNS                              233
#define TRAINER_TERRELL_HNS                           234
#define TRAINER_KENT_HNS                              235
#define TRAINER_ERNEST_HNS                            236
#define TRAINER_JEFF_HNS                              237
#define TRAINER_GARRETT_HNS                           238
#define TRAINER_KENNETH_HNS                           239
#define TRAINER_STANLY_HNS                            240
#define TRAINER_HARRY_HNS                             241
#define TRAINER_STAN_HNS                              242
#define TRAINER_ERIC_HNS                              243
#define TRAINER_GREGG_HNS                             244
#define TRAINER_JAY_HNS                               245
#define TRAINER_DAVE_HNS                              246
#define TRAINER_SAM_HNS                               247
#define TRAINER_TOM_HNS                               248
#define TRAINER_PAT_HNS                               249
#define TRAINER_SHAWN_HNS                             250
#define TRAINER_TERU_HNS                              251
#define TRAINER_RUSS_HNS                              252
#define TRAINER_NORTON_HNS                            253
#define TRAINER_HUGH_HNS                              254
#define TRAINER_MARKUS_HNS                            255
#define TRAINER_CLYDE_HNS                             256
#define TRAINER_VINCENT_HNS                           257
#define TRAINER_ANTHONY_HNS                           258
#define TRAINER_RUSSELL_HNS                           259
#define TRAINER_PHILLIP_HNS                           260
#define TRAINER_LEONARD_HNS                           261
#define TRAINER_BENJAMIN_HNS                          262
#define TRAINER_ERIK_HNS                              263
#define TRAINER_MICHAEL_HNS                           264
#define TRAINER_PARRY_HNS                             265
#define TRAINER_TIMOTHY_HNS                           266
#define TRAINER_BAILEY_HNS                            267
#define TRAINER_TIM_HNS                               268
#define TRAINER_NOLAND_HNS                            269
#define TRAINER_SIDNEY_HNS                            270
#define TRAINER_KENNY_HNS                             271
#define TRAINER_JIM_HNS                               272
#define TRAINER_DEVIN_HNS                             273
#define TRAINER_DANIEL_HNS                            274
#define TRAINER_KAZU_HNS                              275
#define TRAINER_DWAYNE_HNS                            276
#define TRAINER_HARRIS_HNS                            277
#define TRAINER_ZEKE_HNS                              278
#define TRAINER_CHARLES_HNS                           279
#define TRAINER_RILEY_HNS                             280
#define TRAINER_JOEL_HNS                              281
#define TRAINER_GLENN_HNS                             282
#define TRAINER_DUNCAN_HNS                            283
#define TRAINER_EDDIE_HNS                             284
#define TRAINER_RICHARDO_HNS                          285
#define TRAINER_NARD_HNS                              286
#define TRAINER_COREY_HNS                             287
#define TRAINER_OTIS_HNS                              288
#define TRAINER_DICK_HNS                              289
#define TRAINER_NED_HNS                               290
#define TRAINER_BURT_HNS                              291
#define TRAINER_BILL_HNS                              292
#define TRAINER_WALT_HNS                              293
#define TRAINER_RAY_HNS                               294
#define TRAINER_LYLE_HNS                              295
#define TRAINER_IRWIN_HNS                             296
#define TRAINER_FRITZ_HNS                             297
#define TRAINER_HORTON_HNS                            298
#define TRAINER_KENJI_HNS                             299
#define TRAINER_YOSHI_HNS                             300
#define TRAINER_LAO_HNS                               301
#define TRAINER_NOB_HNS                               302
#define TRAINER_KIYO_HNS                              303
#define TRAINER_LUNG_HNS                              304
#define TRAINER_WAI_HNS                               305
#define TRAINER_NATHAN_HNS                            306
#define TRAINER_FRANKLIN_HNS                          307
#define TRAINER_HERMAN_HNS                            308
#define TRAINER_FIDEL_HNS                             309
#define TRAINER_GREG_HNS                              310
#define TRAINER_NORMAN_HNS                            311
#define TRAINER_MARK_HNS                              312
#define TRAINER_PHIL_HNS                              313
#define TRAINER_RICHARD_HNS                           314
#define TRAINER_GILBERT_HNS                           315
#define TRAINER_JARED_HNS                             316
#define TRAINER_RODNEY_HNS                            317
#define TRAINER_LIZ_HNS                               318
#define TRAINER_GINA_HNS                              319
#define TRAINER_BROOKE_HNS                            320
#define TRAINER_KIM_HNS                               321
#define TRAINER_CINDY_HNS                             322
#define TRAINER_HOPE_HNS                              323
#define TRAINER_SHARON_HNS                            324
#define TRAINER_DEBRA_HNS                             325
#define TRAINER_ERIN_HNS                              326
#define TRAINER_HEIDI_HNS                             327
#define TRAINER_EDNA_HNS                              328
#define TRAINER_TIFFANY_HNS                           329
// NOTE: 330 is reserved by TRAINER_FRONTIER_BRAIN (see include/constants/trainers.h).
// Several battle routines compare opponentA against it without first checking for a
// Frontier battle type, so a regular trainer with that ID gets the Frontier Brain's
// pic/name/class and reads gFrontierBrainInfo[VAR_FRONTIER_FACILITY] out of bounds.
// Tanya was moved to 618 for that reason -- do not reuse 330 (or 331, TRAINER_PLAYER).
#define TRAINER_TANYA_HNS                             618
#define TRAINER_ROLAND_HNS                            331
#define TRAINER_TODD_HNS                              332
#define TRAINER_IVAN_HNS                              333
#define TRAINER_ELLIOT_HNS                            334
#define TRAINER_BARRY_HNS                             335
#define TRAINER_LLOYD_HNS                             336
#define TRAINER_DEAN_HNS                              337
#define TRAINER_SID_HNS                               338
#define TRAINER_HARVEY_HNS                            339
#define TRAINER_DALE_HNS                              340
#define TRAINER_TED_HNS                               341
#define TRAINER_THOMAS_HNS                            342
#define TRAINER_LEROY_HNS                             343
#define TRAINER_DAVID_HNS                             344
#define TRAINER_JOHN_HNS                              345
#define TRAINER_JERRY_HNS                             346
#define TRAINER_GRANT_HNS                             347
#define TRAINER_SPENCER_HNS                           348
#define TRAINER_QUENTIN_HNS                           349
#define TRAINER_CHOW_HNS                              350
#define TRAINER_NICO_HNS                              351
#define TRAINER_JIN_HNS                               352
#define TRAINER_TROY_HNS                              353
#define TRAINER_JEFFREY_HNS                           354
#define TRAINER_PING_HNS                              355
#define TRAINER_EDMOND_HNS                            356
#define TRAINER_NEAL_HNS                              357
#define TRAINER_LI_HNS                                358
#define TRAINER_GAKU_HNS                              359
#define TRAINER_MASA_HNS                              360
#define TRAINER_KOJI_HNS                              361
#define TRAINER_MARTHA_HNS                            362
#define TRAINER_GRACE_HNS                             363
#define TRAINER_BETHANY_HNS                           364
#define TRAINER_MARGRET_HNS                           365
#define TRAINER_ETHEL_HNS                             366
#define TRAINER_REBECCA_HNS                           367
#define TRAINER_DORIS_HNS                             368
#define TRAINER_RONALD_HNS                            369
#define TRAINER_BRAD_HNS                              370
#define TRAINER_DOUGLAS_HNS                           371
#define TRAINER_WILLIAM_HNS                           372
#define TRAINER_DEREK_HNS                             373
#define TRAINER_ROBERT_HNS                            374
#define TRAINER_JOSHUA_HNS                            375
#define TRAINER_CARTER_HNS                            376
#define TRAINER_TREVOR_HNS                            377
#define TRAINER_BRANDON_HNS                           378
#define TRAINER_JEREMY_HNS                            379
#define TRAINER_COLIN_HNS                             380
#define TRAINER_ALEX_HNS                              381
#define TRAINER_REX_HNS                               382
#define TRAINER_ALLAN_HNS                             383
#define TRAINER_NAOKO_HNS                             384
#define TRAINER_SAYO_HNS                              385
#define TRAINER_ZUKI_HNS                              386
#define TRAINER_KUNI_HNS                              387
#define TRAINER_MIKI_HNS                              388
#define TRAINER_AMY_AND_MAY_HNS                       389
#define TRAINER_ANN_AND_ANNE_HNS                      390
#define TRAINER_JO_AND_ZOE_HNS                        391
#define TRAINER_MEG_AND_PEG_HNS                       392
#define TRAINER_LEA_AND_PIA_HNS                       393
#define TRAINER_BEVERLY_HNS                           394
#define TRAINER_RUTH_HNS                              395
#define TRAINER_GEORGIA_HNS                           396
#define TRAINER_JAMIE_HNS                             397
#define TRAINER_KEITH_HNS                             398
#define TRAINER_DIRK_HNS                              399
#define TRAINER_THOM_AND_KAE_HNS                      400
#define TRAINER_DUFF_AND_EDA_HNS                      401
#define TRAINER_FALKNER_1_HNS                         402
#define TRAINER_FALKNER_2_HNS                         403
#define TRAINER_BUGSY_1_HNS                           404
#define TRAINER_BUGSY_2_HNS                           405
#define TRAINER_WHITNEY_1_HNS                         406
#define TRAINER_WHITNEY_2_HNS                         407
#define TRAINER_MORTY_1_HNS                           408
#define TRAINER_MORTY_2_HNS                           409
#define TRAINER_PRYCE_1_HNS                           410
#define TRAINER_PRYCE_2_HNS                           411
#define TRAINER_PRYCE_1_2_HNS                         412
#define TRAINER_PRYCE_1_3_HNS                         413
#define TRAINER_JASMINE_1_HNS                         414
#define TRAINER_JASMINE_2_HNS                         415
#define TRAINER_JASMINE_1_2_HNS                       416
#define TRAINER_JASMINE_1_3_HNS                       417
#define TRAINER_CHUCK_1_HNS                           418
#define TRAINER_CHUCK_2_HNS                           419
#define TRAINER_CHUCK_1_2_HNS                         420
#define TRAINER_CHUCK_1_3_HNS                         421
#define TRAINER_CLAIR_1_HNS                           422
#define TRAINER_CLAIR_2_HNS                           423
#define TRAINER_BROCK_HNS                             424
#define TRAINER_MISTY_HNS                             425
#define TRAINER_LTSURGE_HNS                           426
#define TRAINER_ERIKA_HNS                             427
#define TRAINER_SABRINA_HNS                           428
#define TRAINER_JANINE_HNS                            429
#define TRAINER_BLAINE_HNS                            430
#define TRAINER_BLUE_HNS                              431
#define TRAINER_BLUE_2_HNS                            432
#define TRAINER_WILL_1_HNS                            433
#define TRAINER_WILL_2_HNS                            434
#define TRAINER_BRUNO_1_HNS                           435
#define TRAINER_BRUNO_2_HNS                           436
#define TRAINER_KAREN_1_HNS                           437
#define TRAINER_KAREN_2_HNS                           438
#define TRAINER_KOGA_1_HNS                            439
#define TRAINER_KOGA_2_HNS                            440
#define TRAINER_LANCE_1_HNS                           441
#define TRAINER_LANCE_2_HNS                           442
#define TRAINER_RIVAL_CHIKORITA_1_HNS                 443
#define TRAINER_RIVAL_CHIKORITA_2_HNS                 444
#define TRAINER_RIVAL_CHIKORITA_3_HNS                 445
#define TRAINER_RIVAL_CHIKORITA_4_HNS                 446
#define TRAINER_RIVAL_CHIKORITA_5_HNS                 447
#define TRAINER_RIVAL_CHIKORITA_6_HNS                 448
#define TRAINER_RIVAL_CHIKORITA_7_HNS                 449
#define TRAINER_RIVAL_CYNDAQUIL_1_HNS                 450
#define TRAINER_RIVAL_CYNDAQUIL_2_HNS                 451
#define TRAINER_RIVAL_CYNDAQUIL_3_HNS                 452
#define TRAINER_RIVAL_CYNDAQUIL_4_HNS                 453
#define TRAINER_RIVAL_CYNDAQUIL_5_HNS                 454
#define TRAINER_RIVAL_CYNDAQUIL_6_HNS                 455
#define TRAINER_RIVAL_CYNDAQUIL_7_HNS                 456
#define TRAINER_RIVAL_TOTODILE_1_HNS                  457
#define TRAINER_RIVAL_TOTODILE_2_HNS                  458
#define TRAINER_RIVAL_TOTODILE_3_HNS                  459
#define TRAINER_RIVAL_TOTODILE_4_HNS                  460
#define TRAINER_RIVAL_TOTODILE_5_HNS                  461
#define TRAINER_RIVAL_TOTODILE_6_HNS                  462
#define TRAINER_RIVAL_TOTODILE_7_HNS                  463
#define TRAINER_RED_HNS                             464
#define TRAINER_EUSINE_HNS                            465
#define TRAINER_GIOVANNI_HNS                          466
#define TRAINER_PROTON_1_HNS                          467
#define TRAINER_PROTON_2_HNS                          468
#define TRAINER_ARCHER_HNS                            469
#define TRAINER_ARCHER_1_HNS                          470
#define TRAINER_ARCHER_4_HNS                          471
#define TRAINER_ARCHER_5_HNS                          472
#define TRAINER_PETREL_1_HNS                          473
#define TRAINER_PETREL_2_HNS                          474
#define TRAINER_ARIANA_1_HNS                          475
#define TRAINER_ARIANA_2_HNS                          476
#define TRAINER_ANABEL_BF_BRAIN_HNS                   477
#define TRAINER_TUCKER_BF_BRAIN_HNS                   478
#define TRAINER_SPENSER_BF_BRAIN_HNS                  479
#define TRAINER_GRETA_BF_BRAIN_HNS                    480
#define TRAINER_NOLAND_BF_BRAIN_HNS                   481
#define TRAINER_LUCY_BF_BRAIN_HNS                     482
#define TRAINER_BRANDON_BF_BRAIN_HNS                  617
#define TRAINER_JOEY_2_HNS                            483
#define TRAINER_JOEY_3_HNS                            484
#define TRAINER_JOEY_4_HNS                            485
#define TRAINER_JOEY_5_HNS                            486
#define TRAINER_WADE_2_HNS                            487
#define TRAINER_WADE_3_HNS                            488
#define TRAINER_WADE_4_HNS                            489
#define TRAINER_WADE_5_HNS                            490
#define TRAINER_RALPH_2_HNS                           491
#define TRAINER_RALPH_3_HNS                           492
#define TRAINER_RALPH_4_HNS                           493
#define TRAINER_RALPH_5_HNS                           494
#define TRAINER_LIZ_2_HNS                             495
#define TRAINER_LIZ_3_HNS                             496
#define TRAINER_LIZ_4_HNS                             497
#define TRAINER_LIZ_5_HNS                             498
#define TRAINER_ANTHONY_2_HNS                         499
#define TRAINER_ANTHONY_3_HNS                         500
#define TRAINER_ANTHONY_4_HNS                         501
#define TRAINER_ANTHONY_5_HNS                         502
#define TRAINER_TODD_2_HNS                            503
#define TRAINER_TODD_3_HNS                            504
#define TRAINER_TODD_4_HNS                            505
#define TRAINER_TODD_5_HNS                            506
#define TRAINER_GINA_2_HNS                            507
#define TRAINER_GINA_3_HNS                            508
#define TRAINER_GINA_4_HNS                            509
#define TRAINER_GINA_5_HNS                            510
#define TRAINER_ARNIE_2_HNS                           511
#define TRAINER_ARNIE_3_HNS                           512
#define TRAINER_ARNIE_4_HNS                           513
#define TRAINER_ARNIE_5_HNS                           514
#define TRAINER_ALAN_2_HNS                            515
#define TRAINER_ALAN_3_HNS                            516
#define TRAINER_ALAN_4_HNS                            517
#define TRAINER_ALAN_5_HNS                            518
#define TRAINER_DANA_2_HNS                            519
#define TRAINER_DANA_3_HNS                            520
#define TRAINER_DANA_4_HNS                            521
#define TRAINER_DANA_5_HNS                            522
#define TRAINER_CHAD_2_HNS                            523
#define TRAINER_CHAD_3_HNS                            524
#define TRAINER_CHAD_4_HNS                            525
#define TRAINER_CHAD_5_HNS                            526
#define TRAINER_TULLY_2_HNS                           527
#define TRAINER_TULLY_3_HNS                           528
#define TRAINER_TULLY_4_HNS                           529
#define TRAINER_BRENT_2_HNS                           530
#define TRAINER_BRENT_3_HNS                           531
#define TRAINER_BRENT_4_HNS                           532
#define TRAINER_TIFFANY_2_HNS                         533
#define TRAINER_TIFFANY_3_HNS                         534
#define TRAINER_TIFFANY_4_HNS                         535
#define TRAINER_VANCE_2_HNS                           536
#define TRAINER_VANCE_3_HNS                           537
#define TRAINER_WILTON_2_HNS                          538
#define TRAINER_WILTON_3_HNS                          539
#define TRAINER_KENJI_2_HNS                           540
#define TRAINER_PARRY_2_HNS                           541
#define TRAINER_PARRY_3_HNS                           542
#define TRAINER_ERIN_2_HNS                            543
#define TRAINER_ERIN_3_HNS                            544
#define TRAINER_JACK_2_HNS                            545
#define TRAINER_JACK_3_HNS                            546
#define TRAINER_JACK_4_HNS                            547
#define TRAINER_JACK_5_HNS                            548
#define TRAINER_HUEY_2_HNS                            549
#define TRAINER_HUEY_3_HNS                            550
#define TRAINER_HUEY_4_HNS                            551
#define TRAINER_GAVEN_2_HNS                           552
#define TRAINER_GAVEN_3_HNS                           553
#define TRAINER_BETH_2_HNS                            554
#define TRAINER_BETH_3_HNS                            555
#define TRAINER_JOSE_2_HNS                            556
#define TRAINER_JOSE_3_HNS                            557
#define TRAINER_REENA_2_HNS                           558
#define TRAINER_REENA_3_HNS                           559
#define TRAINER_LANCE_3_HNS                           560
#define TRAINER_CLAIR_3_HNS                           561
#define TRAINER_ALEX_2_HNS                            562
#define TRAINER_ALEX_3_HNS                            563
#define TRAINER_RILEY_2_HNS                           564
#define TRAINER_RILEY_3_HNS                           565
#define TRAINER_RILEY_4_HNS                           566
#define TRAINER_TREVOR_2_HNS                          567
#define TRAINER_TREVOR_3_HNS                          568
#define TRAINER_KYLE_2_HNS                            569
#define TRAINER_KYLE_3_HNS                            570
#define TRAINER_CARTER_2_HNS                          571
#define TRAINER_CARTER_3_HNS                          572
#define TRAINER_HILLARY_2_HNS                         573
#define TRAINER_HILLARY_3_HNS                         574
#define TRAINER_ROB_2_HNS                             575
#define TRAINER_ROB_3_HNS                             576
#define TRAINER_NICOLE_2_HNS                          577
#define TRAINER_NICOLE_3_HNS                          578
#define TRAINER_BILLY_2_HNS                           579
#define TRAINER_BILLY_3_HNS                           580
#define TRAINER_KENNY_2_HNS                           581
#define TRAINER_KENNY_3_HNS                           582
#define TRAINER_JOEL_2_HNS                            583
#define TRAINER_JOEL_3_HNS                            584
#define TRAINER_CHARLES_2_HNS                         585
#define TRAINER_CHARLES_3_HNS                         586
#define TRAINER_SAMSON_OAK_HNS                        587
#define TRAINER_PHANTONOMY_UNUSED_HNS                 588
#define TRAINER_MELEMELE_SWIMMER_1_HNS                589
#define TRAINER_MELEMELE_SWIMMER_2_HNS                590
#define TRAINER_AKALA_SWIMMER_1_HNS                   591
#define TRAINER_AKALA_SWIMMER_2_HNS                   592
#define TRAINER_PONI_SWIMMER_1_HNS                    593
#define TRAINER_PONI_SWIMMER_2_HNS                    594
#define TRAINER_AKALA_HIKER_HNS                       595
#define TRAINER_AKALA_PICNICKER_HNS                   596
#define TRAINER_AKALA_CAMPER_HNS                      597
#define TRAINER_AKALA_FOREST_BUGCATCHER_1_HNS         598
#define TRAINER_AKALA_FOREST_BUGCATCHER_2_HNS         599
#define TRAINER_AKALA_CAVE_PICNICKER_HNS              600
#define TRAINER_AKALA_CAVE_CAMPER_HNS                 601
#define TRAINER_AKALA_CAVE_HIKER_HNS                  602
#define TRAINER_ULAULA_PICNICKER_HNS                  603
#define TRAINER_ULAULA_YOUNGSTER_HNS                  604
#define TRAINER_ULAULA_HIKER_HNS                      605
#define TRAINER_ULAULA_COOLTRAINER_HNS                606
#define TRAINER_AKALA_SWIMMER_3_HNS                   607

#define TRAINER_MILKMAN_HNS                           608
#define TRAINER_MIHARU_HNS                            609
#define TRAINER_YOUKO_HNS                             610
#define TRAINER_SHIZUKO_HNS                           611
#define TRAINER_STEVEN_HNS                            612
#define TRAINER_FINLEY_HNS                            613
#define TRAINER_MUALANI_HNS                           614
#define TRAINER_WESSEL_HNS                            615
#define TRAINER_SKYLAR_HNS                            616


// Phone rematch tiers for Irwin, Derek and Beverly. Appended at the end of the list
// on purpose: trainer IDs index FLAG_TRAINER_FLAG_START, so inserting mid-list
// would shift every later trainer's "defeated" flag and corrupt existing saves.
#define TRAINER_IRWIN_2_HNS                   619
#define TRAINER_IRWIN_3_HNS                   620
#define TRAINER_IRWIN_4_HNS                   621
#define TRAINER_IRWIN_5_HNS                   622
#define TRAINER_DEREK_2_HNS                   623
#define TRAINER_DEREK_3_HNS                   624
#define TRAINER_DEREK_4_HNS                   625
#define TRAINER_DEREK_5_HNS                   626
#define TRAINER_BEVERLY_2_HNS                 627
#define TRAINER_BEVERLY_3_HNS                 628
#define TRAINER_BEVERLY_4_HNS                 629
#define TRAINER_BEVERLY_5_HNS                 630

// 618 is TRAINER_TANYA_HNS, relocated out of the TRAINER_FRONTIER_BRAIN slot (330).

// Post-OBC (Battle Championship) rematch teams for the Gym Leaders, Elite Four,
// Lance, Blue and Red. Appended at the end of the list for the same save-index
// reason as the phone rematch tiers above.
#define TRAINER_FALKNER_POSTOBC_HNS           631
#define TRAINER_BUGSY_POSTOBC_HNS             632
#define TRAINER_WHITNEY_POSTOBC_HNS           633
#define TRAINER_MORTY_POSTOBC_HNS             634
#define TRAINER_CHUCK_POSTOBC_HNS             635
#define TRAINER_JASMINE_POSTOBC_HNS           636
#define TRAINER_PRYCE_POSTOBC_HNS             637
#define TRAINER_CLAIR_POSTOBC_HNS             638
#define TRAINER_BROCK_POSTOBC_HNS             639
#define TRAINER_LTSURGE_POSTOBC_HNS           640
#define TRAINER_JANINE_POSTOBC_HNS            641
#define TRAINER_SABRINA_POSTOBC_HNS           642
#define TRAINER_BLAINE_POSTOBC_HNS            643
#define TRAINER_BLUE_POSTOBC_HNS              644
#define TRAINER_WILL_POSTOBC_HNS              645
#define TRAINER_KOGA_POSTOBC_HNS              646
#define TRAINER_BRUNO_POSTOBC_HNS             647
#define TRAINER_KAREN_POSTOBC_HNS             648
#define TRAINER_LANCE_POSTOBC_HNS             649
#define TRAINER_RED_POSTOBC_HNS               650
#define TRAINER_MISTY_POSTOBC_HNS             651
#define TRAINER_ERIKA_POSTOBC_HNS             652
#define TRAINER_CYNTHIA_HNS                   653

#define TRAINERS_COUNT_HNS                       654
#define MAX_TRAINERS_COUNT_HNS                   864

#endif  // GUARD_CONSTANTS_OPPONENTS_HNS_H
