UnionCave_1F_hns_MapScripts::
	.byte 0


UnionCave_1F_Trigger_Monview::
	special SpawnCameraObject
	applymovement2 OBJ_EVENT_ID_CAMERA, Common_Movement_WalkRight1
	waitmovement 0
	applymovement2 OBJ_EVENT_ID_CAMERA, Common_Movement_WalkRight1
	waitmovement 0
	applymovement2 OBJ_EVENT_ID_CAMERA, Common_Movement_WalkRight1
	waitmovement 0
	applymovement2 OBJ_EVENT_ID_CAMERA, Common_Movement_WalkRight1
	waitmovement 0
	message Route29_Text_PressAorB
	waitbuttonpress
	closemessage
	applymovement2 OBJ_EVENT_ID_CAMERA, Common_Movement_WalkLeft1
	waitmovement 0
	applymovement2 OBJ_EVENT_ID_CAMERA, Common_Movement_WalkLeft1
	waitmovement 0
	applymovement2 OBJ_EVENT_ID_CAMERA, Common_Movement_WalkLeft1
	waitmovement 0
	applymovement2 OBJ_EVENT_ID_CAMERA, Common_Movement_WalkLeft1
	waitmovement 0
	special RemoveCameraObject
	applymovement2 OBJ_EVENT_ID_PLAYER, Common_Movement_WalkLeft1
	waitmovement 0
	end


UnionCave_1F_EventScript_HikerRussell::
	trainerbattle_single TRAINER_RUSSELL_HNS, UnionCave_1F_Text_HikerRussellSeen, UnionCave_1F_Text_HikerRussellBeaten
	msgbox UnionCave_1F_Text_HikerRussellAfter, MSGBOX_AUTOCLOSE
	end

UnionCave_1F_EventScript_PokemaniacLarry::
	trainerbattle_single TRAINER_LARRY_HNS, UnionCave_1F_Text_PokemaniacLarrySeen, UnionCave_1F_Text_PokemaniacLarryBeaten
	msgbox UnionCave_1F_Text_PokemaniacLarryAfter, MSGBOX_AUTOCLOSE
	end

UnionCave_1F_EventScript_HikerDaniel::
	trainerbattle_single TRAINER_DANIEL_HNS, UnionCave_1F_Text_HikerDanielSeen, UnionCave_1F_Text_HikerDanielBeaten
	msgbox UnionCave_1F_Text_HikerDanielAfter, MSGBOX_AUTOCLOSE
	end

UnionCave_1F_EventScript_FirebreatherBill::
	trainerbattle_single TRAINER_BILL_HNS, UnionCave_1F_Text_FirebreatherBillSeen, UnionCave_1F_Text_FirebreatherBillBeaten
	msgbox UnionCave_1F_Text_FirebreatherBillAfter, MSGBOX_AUTOCLOSE
	end

UnionCave_1F_EventScript_FirebreatherRay::
	trainerbattle_single TRAINER_RAY_HNS, UnionCave_1F_Text_FirebreatherRaySeen, UnionCave_1F_Text_FirebreatherRayBeaten
	msgbox UnionCave_1F_Text_FirebreatherRayAfter, MSGBOX_AUTOCLOSE
	end	

UnionCave_1F_EventScript_Item_Potion::
	finditem ITEM_POTION
	end

UnionCave_1F_EventScript_Item_GreatBall::
	finditem ITEM_GREAT_BALL
	end

UnionCave_1F_EventScript_Item_Xattack::
	finditem ITEM_X_ATTACK
	end

UnionCave_1F_EventScript_Item_Awakening::
	finditem ITEM_AWAKENING
	end

UnionCave_1F_Text_HikerRussellSeen:
	.string "You're headed to AZALEA, are you?\p"
	.string "Let my MOéMON see if you are good\n"
	.string "enough to battle.$"

UnionCave_1F_Text_HikerRussellBeaten:
	.string "Oh, oh, oh!$"

UnionCave_1F_Text_HikerRussellAfter:
	.string "All right, then! I've decided.\p"
	.string "I'm not leaving until my MOéMON\n"
	.string "get tougher!$"

UnionCave_1F_Text_PokemaniacLarrySeen:
	.string "I roam far and wide in search of\n"
	.string "MOéMON.\p"
	.string "Are you looking for MOéMON too?\p"
	.string "Then you're my collecting rival!$"

UnionCave_1F_Text_PokemaniacLarryBeaten:
	.string "Ugh. My poor MOéMON…$"

UnionCave_1F_Text_PokemaniacLarryAfter:
	.string "Sometimes, you can hear MOéMON\n"
	.string "roars from deep inside the cave.$"

UnionCave_1F_Text_HikerDanielSeen:
	.string "Whoa! What a surprise!\p"
	.string "I didn't expect to see anyone here!$"

UnionCave_1F_Text_HikerDanielBeaten:
	.string "Whoa! I'm beaten big time!$"

UnionCave_1F_Text_HikerDanielAfter:
	.string "I was conned into buying a\n"
	.string "SLOWPOKETAIL.\p"
	.string "I feel sorry for the poor MOéMON.$"

UnionCave_1F_Text_FirebreatherBillSeen:
	.string "ZUBAT's SUPERSONIC keeps confusing\n"
	.string "my MOéMON.\p"
	.string "I'm seriously upset about that!$"

UnionCave_1F_Text_FirebreatherBillBeaten:
	.string "I flamed out!$"

UnionCave_1F_Text_FirebreatherBillAfter:
	.string "On weekends, you can hear strange\n"
	.string "roars from deep in the cave.$"

UnionCave_1F_Text_FirebreatherRaySeen:
	.string "If it's light, a cave isn't scary.\p"
	.string "If you're strong, MOéMON aren't\n"
	.string "scary.$"

UnionCave_1F_Text_FirebreatherRayBeaten:
	.string "FLASH!$"

UnionCave_1F_Text_FirebreatherRayAfter:
	.string "It's my MOéMON's fire that lights\n"
	.string "up this cave.$"
