gText_Oak_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of MOéMON!\p"
	.string "My name is OAK.\p"
	.string "People call me the MOéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Oak_Pokemon::
	.string "This is what we call a “MOéMON.”\p"
	.string "\n"
	.string "$"

gText_Oak_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as MOéMON.\p"
	.string "People and MOéMON live together,\n"
	.string "by supporting each other.\p"
	.string "Some people play with MOéMON,\n"
	.string "some battle with them. \p"
	.string "But we don't know everything about\n"
	.string "MOéMON yet. \p"
	.string "There are still many mysteries\n"
	.string "to solve. That's why I study\l"
	.string "MOéMON every day.\p"
	.string "$"

gText_Oak_AndYouAre::
	.string "And you are?$"

gText_Oak_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Oak_WhatChallenge::
	.string "What challenge are you\n"
	.string "expecting?$"

gText_Oak_ChallengeSelected::
	.string "That sounds like the right\n"
	.string "level of challenge to me!$" 

gText_Oak_WhatsYourName::
	.string "And what's your name?$"

gText_Oak_SoItsPlayer::
	.string "Oh! So you're {PLAYER}{KUN}?$"

gText_Oak_YourePlayer::
	.string "{PLAYER}{KUN}, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "$"

gText_Oak_AreYouReady::
	.string "You'll face fun times and tough\n"
	.string "challenges.\p"
	.string "A world of dreams and adventures\n"
	.string "with MOéMON awaits! Let's go!\p"
	.string "I'll be seeing you later!\p"
	.string "$"
