gBirchDexRatingText_AreYouCurious::
	.string "PROF. BIRCH: Ah, {PLAYER}{KUN}!\p"
	.string "Are you curious about how your\n"
	.string "MOéDEX is coming along?$"

gBirchDexRatingText_Cancel::
	.string "Hm? Oh, you haven't caught enough\n"
	.string "MOéMON to make it worthwhile.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm…\p"
	.string "So, you've seen {STR_VAR_1} MOéMON,\n"
	.string "and you've caught {STR_VAR_2} MOéMON…$"

gBirchDexRatingText_LessThan10::
	.string "Go into grassy areas more and look\n"
	.string "for MOéMON more carefully.$"

gBirchDexRatingText_LessThan20::
	.string "I guess you're getting the hang\n"
	.string "of it. But, it gets harder from here.$"

gBirchDexRatingText_LessThan30::
	.string "Some MOéMON only appear in\n"
	.string "certain areas.\l"
	.string "You must be persistent.$"

gBirchDexRatingText_LessThan40::
	.string "Well, it could use more quantity,\n"
	.string "but this is looking more like\l"
	.string "a MOéDEX now.$"

gBirchDexRatingText_LessThan50::
	.string "This is coming along pretty good.\n"
	.string "Keep up the effort.$"

gBirchDexRatingText_LessThan60::
	.string "Are you using any RODS?\n"
	.string "There are many MOéMON in the sea.$"

gBirchDexRatingText_LessThan70::
	.string "Instead of just catching MOéMON,\n"
	.string "how about making them evolve, too?$"

gBirchDexRatingText_LessThan80::
	.string "This is going to be a fantastic\n"
	.string "MOéDEX.\l"
	.string "That's the feeling I'm getting.$"

gBirchDexRatingText_LessThan90::
	.string "You've collected this many…\n"
	.string "Your talent is remarkable!$"

gBirchDexRatingText_LessThan100::
	.string "Have you visited the SAFARI ZONE?\p"
	.string "I hear there are some MOéMON that\n"
	.string "can only be caught there.$"

gBirchDexRatingText_LessThan110::
	.string "You've finally reached\n"
	.string "the 100-kind mark.\p"
	.string "This is an impressive MOéDEX!$"

gBirchDexRatingText_LessThan120::
	.string "There might be MOéMON that can be\n"
	.string "found using ROCK SMASH.$"

gBirchDexRatingText_LessThan130::
	.string "You should get some more MOéMON\n"
	.string "by trading with others.$"

gBirchDexRatingText_LessThan140::
	.string "I've heard of MOéMON that evolve\n"
	.string "when they come to fully love their\l"
	.string "TRAINERS.$"

gBirchDexRatingText_LessThan150::
	.string "I had no idea that there were so\n"
	.string "many MOéMON species in the HOENN\l"
	.string "region.$"

gBirchDexRatingText_LessThan160::
	.string "On occasion, some MOéMON appear\n"
	.string "in large numbers like outbreaks.\p"
	.string "Don't miss opportunities like\n"
	.string "those.$"

gBirchDexRatingText_LessThan170::
	.string "One can get a very good idea about\n"
	.string "the MOéMON of the HOENN region\l"
	.string "by looking through your MOéDEX.$"

gBirchDexRatingText_LessThan180::
	.string "I would say you already qualify as\n"
	.string "a MOéMON PROFESSOR, and a good\l"
	.string "one, too!$"

gBirchDexRatingText_LessThan190::
	.string "With a MOéDEX this complete,\n"
	.string "you're a real professional at this!$"

gBirchDexRatingText_LessThan200::
	.string "You're very close to completing\n"
	.string "this MOéDEX.\l"
	.string "I can feel it in my bones!$"

gBirchDexRatingText_DexCompleted::
	.string "Congratulations!\n"
	.string "Your MOéDEX is complete!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmhm…\n"
	.string "On a nationwide basis…\p"
	.string "You've seen {STR_VAR_1} MOéMON,\n"
	.string "and you've caught {STR_VAR_2} MOéMON…$"

@ FRLG

PokedexRating_Text_HowIsPokedexComingAlong::
	.string "OAK: Good to see you!\n"
	.string "How is your MOéDEX coming along?\p"
	.string "Here, let me take a look.$"

PokedexRating_Text_SeenXOwnedY::
	.string "The amount of progress you've made\n"
	.string "on your MOéDEX is:\p"
	.string "{STR_VAR_1} MOéMON seen and\n"
	.string "{STR_VAR_2} MOéMON owned.\p"
	.string "{FONT_NORMAL}PROF. OAK's rating:$"

PokedexRating_Text_LessThan10::
	.string "You still have lots to do.\p"
	.string "Go into every patch of grass you\n"
	.string "see and look for MOéMON!$"

PokedexRating_Text_LessThan20::
	.string "It looks as if you're getting on\n"
	.string "the right track!\p"
	.string "I've given one of my AIDES a FLASH\n"
	.string "HM. Make sure you go get it!$"

PokedexRating_Text_LessThan30::
	.string "Your MOéDEX could use a bit more\n"
	.string "volume still!\p"
	.string "Try to catch other species of\n"
	.string "MOéMON!$"

PokedexRating_Text_LessThan40::
	.string "Good, it's apparent that you're\n"
	.string "trying hard!\p"
	.string "I've given one of my AIDES an\n"
	.string "ITEMFINDER. Be sure to collect it!$"

PokedexRating_Text_LessThan50::
	.string "Your MOéDEX is coming along quite\n"
	.string "well!\p"
	.string "I've given one of my AIDES an\n"
	.string "AMULET COIN. Be sure to get it!$"

PokedexRating_Text_LessThan60::
	.string "Ah, you've finally topped 50\n"
	.string "species!\p"
	.string "I've given one of my AIDES an EXP.\n"
	.string "SHARE. Be sure to go get it!$"

PokedexRating_Text_LessThan70::
	.string "Hoho! This is turning into quite the\n"
	.string "respectable MOéDEX!$"

PokedexRating_Text_LessThan80::
	.string "Very good!\p"
	.string "I think you'll collect even more\n"
	.string "MOéMON by going fishing!$"

PokedexRating_Text_LessThan90::
	.string "Wonderful! Let me guess… You\n"
	.string "like to collect things, don't you?$"

PokedexRating_Text_LessThan100::
	.string "I'm impressed!\n"
	.string "It must have been difficult to do!$"

PokedexRating_Text_LessThan110::
	.string "You've finally hit 100 species!\n"
	.string "I can't believe how good you are!$"

PokedexRating_Text_LessThan120::
	.string "You even have the evolved forms\n"
	.string "of MOéMON! Super!$"

PokedexRating_Text_LessThan130::
	.string "Excellent! Trade with friends to\n"
	.string "get some more!$"

PokedexRating_Text_LessThan140::
	.string "Outstanding!\n"
	.string "You've become a real pro at this!$"

PokedexRating_Text_LessThan150::
	.string "I have nothing left to say!\n"
	.string "You're the MOéMON PROFESSOR now!$"

PokedexRating_Text_Complete::
	.string "Your MOéDEX is entirely complete!\n"
	.string "Congratulations!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "And your NATIONAL MOéDEX is:\p"
	.string "{STR_VAR_1} MOéMON seen and\n"
	.string "{STR_VAR_2} MOéMON owned.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "I'll be looking forward to seeing\n"
	.string "you fill the NATIONAL MOéDEX!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Finally…\p"
	.string "You've finally completed the\n"
	.string "MOéDEX!\p"
	.string "It's magnificent!\n"
	.string "Truly, this is a fantastic feat!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Wroooooooaaaaaarrrr!$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Thank you, {PLAYER}!\n"
	.string "Sincerely, thank you!\l"
	.string "You've made my dream a reality!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "OAK: Ah, welcome!\p"
	.string "Tell me, how is your MOéDEX\n"
	.string "coming along?\p"
	.string "Wahaha!\p"
	.string "Actually, I know how it is, but I\n"
	.string "love seeing it anyway!\p"
	.string "Let's see…$"

@ HnS (mostly directly copied from HGSS)

gElmDexRatingText_GoFindMrPokemon::
	.string "PROF. ELM: Ah, {PLAYER}{KUN}!\p"
	.string "Have you found MR. MOéMON's\n"
	.string "home yet? It is on ROUTE 30,\p"
	.string "you can't miss it!$"

gElmDexRatingText_Robbery::
	.string "PROF. ELM: {PLAYER}{KUN}!\p"
	.string "Get here quick! Something\n"
	.string "awful has happened!$"

gElmDexRatingText_AreYouCurious::
	.string "PROF. ELM: Ah, {PLAYER}{KUN}!\p"
	.string "Are you curious about how your\n"
	.string "MOéDEX is coming along?$"

gElmDexRatingText_AreYouCuriousNational::
	.string "PROF. ELM: Ah, {PLAYER}{KUN}!\p"
	.string "Are you curious about how your\n"
	.string "National MOéDEX is coming along?$"

gJohtoDexRatingText_LessThan10::
	.string "Look for MOéMON in grassy areas!$"

gJohtoDexRatingText_LessThan20::
	.string "Good. I see you understand how to\n"
	.string "use Poké Balls.$"

gJohtoDexRatingText_LessThan35::
	.string "You're getting good at this,\n"
	.string "but you have a long way to go.$"

gJohtoDexRatingText_LessThan50::
	.string "Hmm, you're catching MOéMON at a\n"
	.string "decent pace!$"

gJohtoDexRatingText_LessThan65::
	.string "You're trying--I can see that.\n"
	.string "Your MOéDEX is coming together.$"

gJohtoDexRatingText_LessThan80::
	.string "You're training them well. You know\n"
	.string "some MOéMON don't evolve just by\p"
	.string "battling with others, right?$"

gJohtoDexRatingText_LessThan95::
	.string "Do you have a Fishing Rod?\n"
	.string "There are some MOéMON that can\p"
	.string "only be found by fishing!$"

gJohtoDexRatingText_LessThan110::
	.string "Excellent! You seem to be good at\n"
	.string "collecting things!$"

gJohtoDexRatingText_LessThan125::
	.string "Some MOéMON only appear during\n"
	.string "certain times of the day.$"

gJohtoDexRatingText_LessThan140::
	.string "Your MOéDEX is really filling up.\n"
	.string "Keep up the good work!$"

gJohtoDexRatingText_LessThan155::
	.string "I'm impressed.\n"
	.string "You're evolving MOéMON, not just\p"
	.string "catching them.$"

gJohtoDexRatingText_LessThan170::
	.string "If you can learn how to use the\n"
	.string "custom Poké Balls made by Kurt\p"
	.string "effectively, you'll be able to catch\n"
	.string "MOéMON better!$"

gJohtoDexRatingText_LessThan185::
	.string "When you trade MOéMON, you can\n"
	.string "also trade information. Your\p"
	.string "friends can really help you!$"

gJohtoDexRatingText_LessThan200::
	.string "Are you trading your MOéMON?\n"
	.string "It's tough to do this alone!$"

gJohtoDexRatingText_LessThan215::
	.string "Wow! You've reached 200!\n"
	.string "Your MOéDEX is looking great!$"

@ Taken from Platinum
gJohtoDexRatingText_LessThan230::
	.string "You've proven yourself capable.\n"
    .string "There's nothing to worry about.\p"
    .string "Keep catching MOéMON the way\n"
    .string "you've been doing so far.$"

@ Taken from Platinum
gJohtoDexRatingText_LessThan245::
	.string "Your MOéDEX is well on the way to\n"
	.string "being filled up.\p"
	.string "This MOéDEX can be considered a\n"
	.string "journal of your adventure.$"

gJohtoDexRatingText_LessThan260::
	.string "You've found so many MOéMON!\n"
	.string "You've really helped my studies!$"

gJohtoDexRatingText_LessThan275::
	.string "Magnificent! You have the ability\n"
	.string "to become a great MOéMON\p"
	.string "Professor someday!$"

gJohtoDexRatingText_LessThanMaxDex::
	.string "Your MOéDEX is amazing!\n"
	.string "You're ready to turn professional!$"

gJohtoDexRatingText_Complete::
	.string "Wow!\n"
	.string "That is a complete Johto MOéDEX!\p"  
	.string "Thanks to you, {PLAYER}, the Johto\n"
	.string "MOéDEX is complete!\p"
	.string "Wow...\n"
	.string "You've done an incredible job!$"

gNationalDexRatingText_LessThan100::
	.string "The goal may be far away, but don't\n"
	.string "give up yet! Keep going!$"

gNationalDexRatingText_LessThan150::
	.string "Don't forget, some MOéMON only\n"
	.string "appear at certain times of the day!$"

gNationalDexRatingText_LessThan200::
	.string "If you break rocks, some MOéMON\n"
	.string "that were hiding there might come\p"
	.string "jumping out!$"

gNationalDexRatingText_LessThan250::
	.string "That's wonderful you've been able\n"
	.string "to gather this many MOéMON!\p"
	.string "The path ahead is long. Keep up the\n"
	.string "great work!$"

gNationalDexRatingText_LessThan300::
	.string "If you Headbutt a tree, sometimes\n"
	.string "a MOéMON might fall out!$"

gNationalDexRatingText_LessThan350::
	.string "A lot of MOéMON not found in the\n"
	.string "Johto region like to congregate\p"
	.string "at the Safari Zone$"

gNationalDexRatingText_LessThan400::
@	.string "Music on the radio might also\n"
@	.string "entice MOéMON to leap out$"
	.string "There are hidden locations all\n"
	.string "over the world containing rare\p"
	.string "and unusual MOéMON, try to find\n"
	.string "them all!$"

gNationalDexRatingText_LessThan435::
	.string "Wow, you've gotten so far...!\n"
	.string "I'm actually a little surprised!$"

gNationalDexRatingText_LessThan465::
	.string "This is a critical moment!\n"
	.string "You can't become discouraged!$"

gNationalDexRatingText_LessThan475::
	.string "Just a little more!\n"
	.string "I've got high expectations for you!$"

gNationalDexRatingText_LessThanMaxDex::
	.string "I have never before in all my years\n"
	.string "seen such an incredible Trainer!$"

gNationalDexRatingText_Complete::
	.string "Excellent! That is an amazing\n"
	.string "National MOéDEX!\p"
	.string "Wow...{PAUSE 10}\p"
	.string "You've lived up to my\n"
	.string "expectations wonderfully!\p"
	.string "No, you've exceeded them, {PLAYER}.\n"
	.string "You've become an amazing Trainer!\p"
	.string "Thank you, {PLAYER}!$"
