BattleFrontier_Lounge8_hns_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man_hns::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds_hns, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman_hns::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains_hns, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy_hns::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling_hns, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds_hns:
	.string "What a TRAINER needs…\p"
	.string "Knowledge…\n"
	.string "Strategy…\l"
	.string "Luck…\l"
	.string "Guts…\l"
	.string "Spirit…\l"
	.string "Bravery…\l"
	.string "And ability…\p"
	.string "Well, I'm all set in every way!\n"
	.string "I'll be unstoppable at every building!\p"
	.string "Huh? MOéMON?\n"
	.string "What's that?$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains_hns:
	.string "Do you know about the FRONTIER\n"
	.string "BRAINS?\p"
	.string "That's what SCOTT calls the seven\n"
	.string "special TRAINERS that run the seven\l"
	.string "facilities in the BATTLE FRONTIER.$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling_hns:
	.string "At the BATTLE TOWER, an older girl\n"
	.string "told me that I have a lot of talent\l"
	.string "for battling!\p"
	.string "I like MOéMON CONTESTS more!\p"
	.string "But I'm no good at CONTESTS!\p"
	.string "I guess having talent and liking\n"
	.string "something aren't the same.$"

